export const ReportList = [
  {
    name: 'Miyah Iida Myles',
    position: 'SC1',
    date: '2023-05-07',
    paidAmount: '4000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '50',
    fat: '7.5',
    rate: '50',
    photo:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&s=707b9c33066bf8808c934c8ab394dff6',
  },
  {
    name: 'June Cha',
    position: 'SC2',
    date: '2023-05-07',
    paidAmount: '800',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Cow',
    liter: '20',
    fat: '7.5',
    rate: '40',
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    name: 'Iida Niskanen',
    position: 'SC3',
    date: '2023-05-07',
    paidAmount: '1000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
  {
    name: 'Renee Sims',
    position: 'SC4',
    date: '2023-05-07',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '10',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/women/65.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC5',
    date: '2023-04-04',
    paidAmount: '250',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '5',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Sasha Ho',
    position: 'SC6',
    date: '2023-04-04',
    paidAmount: '1500',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo:
      'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?h=350&auto=compress&cs=tinysrgb',
  },
  {
    name: 'Abdullah Hadley',
    position: 'SC7',
    date: '2023-08-08',
    paidAmount: '4000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&s=a72ca28288878f8404a795f39642a46f',
  },
  {
    name: 'Veeti Seppanen',
    position: 'SC8',
    date: '2023-01-10',
    paidAmount: '4000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/97.jpg',
  },
  {
    name: 'Bonnie Riley',
    position: 'SC9',
    date: '2023-02-02',
    paidAmount: '4000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/women/26.jpg',
  },
  {
    name: 'Miyah Myles',
    position: 'SC10',
    date: '2023-03-04',
    paidAmount: '4000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&s=707b9c33066bf8808c934c8ab394dff6',
  },
  {
    name: 'June Cha',
    position: 'SC11',
    date: '2023-07-19',
    paidAmount: '4000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    name: 'Iida Niskanen',
    date: '2023-07-19',
    paidAmount: '2500',
    position: 'SC12',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/women/68.jpg',
  },
  {
    name: 'Renee Sims',
    position: 'SC13',
    date: '2023-09-09',
    paidAmount: '3000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/women/65.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
  {
    name: 'Jonathan Nu\u00f1ez',
    position: 'SC14',
    date: '2023-11-11',
    paidAmount: '2000',
    notification: '8 liter milk has received by person',
    time: '08:30 am',
    type: 'Buffalo',
    liter: '20',
    fat: '7.5',
    rate: '50',
    photo: 'https://randomuser.me/api/portraits/men/43.jpg',
  },
];
