export const UserData = [
  {
    id: 1,
    fullName: 'Prabhas Vipin',
    MobileNum: '7925624604',
    BusinessName: 'Hotel Management',
    BusinessCategory: 'Food',
    city: 'Kolhapur',
    Address: 'Kolhapur',
    converted: 'No',
    approved: false,
    rejected: true,
  },
  {
    id: 2,
    fullName: 'Gaurang Pashupathy',
    MobileNum: '7555344641',
    BusinessName: 'Alfreds Futterkiste',
    BusinessCategory: 'Maria Anders',
    city: 'Mumbai',
    Address: '2nd Floor, 177-79, Mj Patel House',
    converted: 'Yes',
    approved: true,
    rejected: false,
  },

  {
    id: 4,
    fullName: 'Rajas Tyagri',
    MobileNum: '8028399027',
    BusinessName: 'Alfreds Futterkiste',
    BusinessCategory: 'Maria Anders',
    city: ' Bangalore',
    Address: '163, Shopno 2, 3 Stage, Katthirguppe,',
    converted: 'No',
    approved: false,
    rejected: false,
  },
  {
    id: 5,
    fullName: 'Sana Jamadar',
    MobileNum: '8028399027',
    BusinessName: 'Alfreds Futterkiste',
    BusinessCategory: 'Maria Anders',
    city: 'Hyderabad',
    Address: '5-4-187/3 &4, Mg Road',
    converted: 'No',
    approved: false,
    rejected: true,
  },
  {
    id: 6,
    fullName: 'Indrajit Dalal',
    MobileNum: '2222021143',
    BusinessName: 'Alfreds Futterkiste',
    BusinessCategory: 'Maria Anders',
    city: 'Mumbai',
    Address: 'Prabhakar Kunte Nagar, 90 Feet Road',
    converted: 'No',
    approved: false,
    rejected: true,
  },
  {
    id: 7,
    fullName: 'rohit sharma',
    MobileNum: '2222021143',
    BusinessName: 'Cricket',
    BusinessCategory: 'Batsman',
    city: 'Mumbai',
    Address: 'Prabhakar Kunte Nagar, 90 Feet Road',
    converted: 'No',
    approved: false,
    rejected: true,
  },
];
