export const DATA = [
  {
    id: 1,
    fullName: 'John Doe',
    MobileNum: '85858585',
    BusinessName: 'Hotel Management',
    BusinessCategory: 'Food',
    city: 'Kolhapur',
    Address: 'Kolhapur',
    converted: 'No',
  },
  {
    id: 2,
    fullName: 'Emma Watsom',
    MobileNum: '85858585',
    BusinessName: 'Alfreds Futterkiste',
    BusinessCategory: 'Maria Anders',
    city: 'Maria Anders',
    Address: 'Sales Representative',
    converted: 'Yes',
  },
  {
    id: 3,
    fullName: 'Sana Jamadar',
    MobileNum: '85858585',
    BusinessName: 'Alfreds Futterkiste',
    BusinessCategory: 'Maria Anders',
    city: 'Maria Anders',
    Address: 'Sales Representative',
    converted: 'No',
  },
];
